### ISSUE TITLE
After Restart, Nothing works!

### ISSUE THREAD

**Issue by LlamaDev92** [ByAlperenS/Furnace#1]
Please add an Option the Players can Remove her Furnace after Restart and old furnaces.
I have install this Plugin and no one can use the furnace because IT says, youre Not the Owner.
OP Players cant remove furnaces.
Furnace.yml doenst save playerdata

Pocketmine 3.15.2
Furnace Dev 3

**Comment by ByAlperenS** [comment]
I Will Consider, For Your Comment. Thank you

**Comment by LlamaDev92** [comment]
Thank you very much, this Plugin is really usefull

**Comment by ByAlperenS** [comment]
Can you explain the problem more clearly? I don't fully understand

**Comment by LlamaDev92** [comment]
No Problem
Place a Furnace with youre Plugin.
Restart the Server
Now you can see, youre Not the Owner of the Furnace.
And all old furnaces cant be use.
For Example, i Place 10 Furnaces on Plot with Myplot Plugin, now i Install youre furnace plugin and Restart the Server.
I cant use the 10 Furnaces because i am Not the Owner.
After Restart, the Furnace.yml is Clean and No playerdatas  is saving 
Sorry for my english, i am from germany

**Comment by ByAlperenS** [comment]
I understood properly now. Fark etmez ben de türküm :D

**Comment by ByAlperenS** [comment]
please check the plugin again

**Comment by ByAlperenS** [comment]
And I would be glad if you give stars :)

**Comment by LlamaDev92** [comment]
OK thanks, i'll Check Dev 4 now

**Comment by LlamaDev92** [comment]
I have tested it, works great!
Thank you very much for youre hard Work in this great Plugin.
But can you add a Permission for OP Players can Break Furnaces?

**Comment by ByAlperenS** [comment]
Okay, I will add soon

**Comment by ByAlperenS** [comment]
I would be glad if you give stars

**Comment by LlamaDev92** [comment]
Have this plugin a Release?
Then i can give 5 stars for IT!

**Comment by ByAlperenS** [comment]
I did not understand

**Comment by ByAlperenS** [comment]
please check the plugin again

**Comment by LlamaDev92** [comment]
Now, all works perfectly.
5 stars comming

**Comment by ByAlperenS** [comment]
thank you very much

**Comment by LlamaDev92** [comment]
Yes and thanks for youre hard work!

**Comment by ByAlperenS** [comment]
thank you
